[repository]
name = "hy3"
authors = ["outfoxxed"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "2f28dc810c0e1f42763a1f14fb011c4fce6db8be"],
	["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "d3e20856a9896f28b506195b31407eddc6df2e20"],
	["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "c880e0f00946273ee0304bba9c1de276062d496f"],
	["c5e28ebcfe00a510922779b2c568cfa52a317445", "8ac36f3954619a9a5c1a1bb3296f782452987e82"],
	["3875679755014997776e091ff8903acfb311dd2f", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["cba1ade848feac44b2eda677503900639581c3f4", "584a1b1e357412a1a4ac40dbc6c4e5adaa7ec59b"], # 0.40.0
	["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "b6a777d2714628d2cda8843aec73a700ef269899"], # 0.41.0
	["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "b2c10c0f4d45aa6ef493f88c3eb0a20516fb9d2b"], # 0.41.1
	["918d8340afd652b011b937d29d5eea0be08467f5", "df75070f7fbc1a894fb309dcbb4573034634d036"], # 0.41.2
	["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "93759c8032995eb566008537389543b3e1b4a65c"], # 0.42.0
	["0f594732b063a90d44df8c5d402d658f27471dfe", "e91460d63627cdad417cac2c09897be58094e2e0"], # 0.43.0
	["0c7a7e2d569eeed9d6025f3eef4ea0690d90845d", "4bc32709c7b8f831e39ec2a7921030c08dbdf500"], # 0.44.0
	["4520b30d498daca8079365bdb909a8dea38e8d55", "4bc32709c7b8f831e39ec2a7921030c08dbdf500"], # 0.44.0
]

[hy3]
description = "i3 like tiling for hyprland"
authors = ["outfoxxed"]
output = "build/libhy3.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
	"cmake --build build"
]
