[repository]
name = "hy3"
authors = ["outfoxxed"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "2f28dc810c0e1f42763a1f14fb011c4fce6db8be"],
	["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "d3e20856a9896f28b506195b31407eddc6df2e20"],
	["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "c880e0f00946273ee0304bba9c1de276062d496f"],
	["c5e28ebcfe00a510922779b2c568cfa52a317445", "8ac36f3954619a9a5c1a1bb3296f782452987e82"],
	["3875679755014997776e091ff8903acfb311dd2f", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "6f9719291386d5e3baad211420d60e54e9967ee6"],
	["cba1ade848feac44b2eda677503900639581c3f4", "584a1b1e357412a1a4ac40dbc6c4e5adaa7ec59b"], # 0.40.0
	["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "b6a777d2714628d2cda8843aec73a700ef269899"], # 0.41.0
	["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "b2c10c0f4d45aa6ef493f88c3eb0a20516fb9d2b"], # 0.41.1
	["918d8340afd652b011b937d29d5eea0be08467f5", "df75070f7fbc1a894fb309dcbb4573034634d036"], # 0.41.2
	["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "93759c8032995eb566008537389543b3e1b4a65c"], # 0.42.0
	["0f594732b063a90d44df8c5d402d658f27471dfe", "e91460d63627cdad417cac2c09897be58094e2e0"], # 0.43.0
	["0c7a7e2d569eeed9d6025f3eef4ea0690d90845d", "4bc32709c7b8f831e39ec2a7921030c08dbdf500"], # 0.44.0
	["4520b30d498daca8079365bdb909a8dea38e8d55", "4bc32709c7b8f831e39ec2a7921030c08dbdf500"], # 0.44.0
	["a425fbebe4cf4238e48a42f724ef2208959d66cf", "4c79361db9c065886c163d1cf873889e1e641e44"], # 0.45.0
	["500d2a3580388afc8b620b0a3624147faa34f98b", "4c79361db9c065886c163d1cf873889e1e641e44"], # 0.45.1
	["12f9a0d0b93f691d4d9923716557154d74777b0a", "4c79361db9c065886c163d1cf873889e1e641e44"], # 0.45.2
	["788ae588979c2a1ff8a660f16e3c502ef5796755", "d9eb126b2475a3b60445be8b2ef0bce4eb1ae8b2"], # 0.46.0
	["254fc2bc6000075f660b4b8ed818a6af544d1d64", "d9eb126b2475a3b60445be8b2ef0bce4eb1ae8b2"], # 0.46.1
	["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "d9eb126b2475a3b60445be8b2ef0bce4eb1ae8b2"], # 0.46.2
	["04ac46c54357278fc68f0a95d26347ea0db99496", "a51839bf635d8a8d83629ee56d777a74c48c0da3"], # 0.47.0
	["75dff7205f6d2bd437abfb4196f700abee92581a", "a51839bf635d8a8d83629ee56d777a74c48c0da3"], # 0.47.1
	["882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff", "a51839bf635d8a8d83629ee56d777a74c48c0da3"], # 0.47.2
	["5ee35f914f921e5696030698e74fb5566a804768", "a1f892fa218f6def606ccb1f81ddc2e57d0551b8"], # 0.48.0
	["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "a1f892fa218f6def606ccb1f81ddc2e57d0551b8"], # 0.48.1
	["9958d297641b5c84dcff93f9039d80a5ad37ab00", "f74302dd00fbbd006ecda8acced222c6c5d0f72f"], # 0.49.0
	["c4a4c341568944bd4fb9cd503558b2de602c0213", "b813c13a10cc39c60eada511f6e6a7947d941aab"], # 0.50.0
	["4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc", "b813c13a10cc39c60eada511f6e6a7947d941aab"], # 0.50.1
	["46174f78b374b6cea669c48880877a8bdcf7802f", "4c9b9bf72274fe2ce61c84e4d6223cf7d99a0654"], # 0.51.0
]

[hy3]
description = "i3 like tiling for hyprland"
authors = ["outfoxxed"]
output = "build/libhy3.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build",
	"cmake --build build"
]
